<?php

namespace GestionBundle\Repository\rrhh;

/**
 * TipoLicenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoLicenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
