<?php

namespace GestionBundle\Repository\ventas;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends \Doctrine\ORM\EntityRepository
{

	public function getAllClientes()
	{
		return $this->createQueryBuilder('c')
				     ->orderBy('c.razonSocial', 'ASC')
				     ->getQuery()
				     ->getResult();
	}
}
